spring:
  datasource:
    url: jdbc:mysql://localhost/lookit
    username: "root"
    password: "0302"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    base_url: https://dapi.kakao.com
    redirect_uri: http://localhost:8080/api/auth/login/kakao

logging:
  level:
    io.netty: DEBUG

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expire-period: 36000000
  refresh-token-expire-period: 3600

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2  # 서울 리전
    s3:
      bucket: lookit-bucket
