spring:
  datasource:
    url: "jdbc:mysql://localhost/lookit"
    username: "root"
    password: "0302"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  kakao:
    client_id: 8bf791a8ad271ac1a21d486646375e9e
    base_url: https://dapi.kakao.com
    redirect_uri: http://localhost:8080/api/auth/login/kakao

logging:
  level:
    io.netty: DEBUG

jwt:
  secret-key: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaasdsakdkaewrkjkjareaserjaskjldjaklsdjklsaj
  access-token-expire-period: 36000000
  refresh-token-expire-period: 3600
